server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.138:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
